# 站点设置
theme: jekyll-theme-minimal
title: 从外包迈向大厂之路
subtitle: ----程序员成神之路
SEOTitle: 玉皇大帝的博客 | Yu Blog # 显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-css.jpg # 首页头部背景图
email: sunny0angel@gmail.com # 邮箱地址
description: "这里是 @Yu玉皇大帝 的个人博客。"
keyword: "玉皇大帝的博客, Yu Blog"
# url: # 站点地址, for absolute URL
# baseurl:  # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/sunny0angel/sunny0angel.github.io" # you code repository

# 侧边栏设置
sidebar: true # 是否开启侧边栏                           
# sidebar-avatar: /img/avatar-lew.jpg # 个人头像
# sidebar-about-description: "世界那么大，我想出去看看。" # 个人简介

# 社交配置
# RSS: false # 是否开启rss
# zhihu_username:  # 知乎用户名
# github_username:  # GitHub 用户名
# jianshu_username:   # 简书用户名

author: 玉皇大帝 #你的名字
language: zh-CN #网站使用的语言
timezone: Asia/Tokyo #网站时区

root: / #网站根目录
permalink: :year/:month/:day/:title/ #永久链接格式
permalink_defaults: #永久链接中各部分的默认值

# Directory 目录配置
posts_dir: posts
source_dir: source #资源文件夹，这个文件夹用来存放内容
public_dir: public #公共文件夹，这个文件夹用于存放生成的站点文件
tag_dir: tags #标签文件夹
archive_dir: archives #归档文件夹
category_dir: categories #分类文件夹
#code_dir: downloads/code #Include code 文件夹
i18n_dir: :lang #国际化文件夹
#skip_render: #跳过指定文件的渲染，您可使用 glob 来配置路径

# Writing 写作配置
new_post_name: :title.md # 新文章的文件名称
default_layout: post #默认布局
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0 #把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false #显示草稿
post_asset_folder: false #是否启动资源文件夹
relative_link: false #把链接改为与根目录的相对位址
future: true
highlight: #代码块的设置
enable: true
line_number: true
auto_detect: true
tab_replace:

# Category & Tag 分类 & 标签
default_category: uncategorized #默认分类
category_map: #分类别名
tag_map: #标签别名

# Date / Time format 时间和日期
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination 分页
## Set per_page to 0 to disable pagination
per_page: 10 #每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page #分页目录
